apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uwi3aqp8w-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uwi3aqp8w-go 
  name: uwi3aqp8w-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uwi3aqp8w-go 
